version: "3.8"

services:
  weather-writer:
    build: .
    container_name: weather_writer
    pull_policy: build
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_CONSUME_TOPIC=${KAFKA_CONSUME_TOPIC}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_CONSUMER_GROUP=${KAFKA_CONSUMER_GROUP}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}
      - MONGODB_COLLECTION=${MONGODB_COLLECTION}
    command: uvicorn main:app --host 0.0.0.0 --port 8088
    ports:
      - "8088:8088"
    networks:
      data-station-network:
        ipv4_address: 172.20.14.85

networks:
  data-station-network:
    external: true
