version: "3.8"

services:
  weather-process:
    build: .
    container_name: weather_processor
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_CONSUME_TOPIC=${KAFKA_CONSUME_TOPIC}
      - KAFKA_PRODUCE_TOPIC=${KAFKA_PRODUCE_TOPIC}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_CONSUMER_GROUP=${KAFKA_CONSUMER_GROUP}
    command: uvicorn main:app --host 0.0.0.0 --port 8081
    ports:
      - "8081:8081"
#     networks:
#       data-station-network:
#         ipv4_address: 172.20.14.84

# networks:
#   data-station-network:
#     external: true
