version: "3.8"

services:
  weather-process:
    image: weather_processor_image:latest
    container_name: weather_processor
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_CONSUME_TOPIC=${KAFKA_CONSUME_TOPIC}
      - KAFKA_PRODUCE_TOPIC=${KAFKA_PRODUCE_TOPIC}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
    ports:
      - "8081:8081"
    command: uvicorn main:app --host 0.0.0.0 --port 8081
    networks:
      - weather_network

networks:
  weather_network:
    external: true
